# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9481448f405f64495fb7479e13f4fe71d6a446226787c92bba17984b2d9250d28685866a356d3362d1cfad9996bfc0a12ec73fa61b7cff3fcf75a24bfc042431

test:
  secret_key_base: 128266e5b2a44aacef61f62dcf52246647181cddff4ecd27b8cabb740bbe1823adfab163f2e99275a70fe371f8b811c83e48f7a28740f460a99f9aa9546d017a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
